ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM*
#ARDUINO_LIBS = /usr/share/arduino/libraries
#USR_LIB_PATH = /home/pi/Arduino/libraries
#ARDUINO_LIB_PATH = /home/pi/Arduino/libraries
#USR_LIB_PATH = /usr/share/arduino/libraries
#ARDUINO_LIB_PATH = /usr/share/arduino/libraries
ARDUINO_LIBS = Si7021 Wire
#ARDUINO_SKETCHBOOK = all_sensors.ino
include /usr/share/arduino/Arduino.mk
